name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libcurl4-openssl-dev

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake
        working-directory: ./build
        run: cmake ../cexa

      - name: Build
        working-directory: ./build
        run: cmake --build . -- -j4

      # when tests are added
      #- name: Run tests
      #  working-directory: ./build
      #  run: ./run_tests

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cexa-binary
          path: build/cexa

  security:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run CodeQL Analysis
        uses: github/codeql-action/init@v2
        with:
          languages: cpp

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
