name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Check formatting
        run: |
          find cexa/src -iname *.hpp -o -iname *.cpp | xargs clang-format -style=file -i
          git diff --exit-code
